language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install .
script:
  - pytest
notifications:
  slack: bayeso:FWBoHH9TMqjKUJWkZxCaTNVE
